import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { listBlocks } from "../packages/cli/src/catalog.ts";

const repositoryRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const packageRoot = join(repositoryRoot, "packages", "cli");
const outputPath = join(packageRoot, "src", "embedded_templates.ts");

interface EmbeddedTemplate {
  path: string;
  content: string;
}

interface EmbeddedBlock {
  name: string;
  templates: EmbeddedTemplate[];
}

async function collectEmbeddedBlocks(): Promise<EmbeddedBlock[]> {
  const blocks: EmbeddedBlock[] = [];
  for (const block of listBlocks()) {
    const templates: EmbeddedTemplate[] = [];
    for (const operation of block.operations) {
      if (operation.kind !== "file.create") continue;
      templates.push({
        path: operation.template,
        content: await Deno.readTextFile(
          join(
            packageRoot,
            "blocks",
            block.name,
            ...operation.template.split("/"),
          ),
        ),
      });
    }
    if (templates.length > 0) blocks.push({ name: block.name, templates });
  }
  return blocks;
}

function renderEmbeddedTemplates(blocks: EmbeddedBlock[]): string {
  const entries = blocks.map((block) => {
    const templates = block.templates.map((template) =>
      `      [${JSON.stringify(template.path)}, ${
        JSON.stringify(template.content)
      }],`
    ).join("\n");
    return `  [
    ${JSON.stringify(block.name)},
    new Map([
${templates}
    ]),
  ],`;
  }).join("\n");

  return `// Generated by scripts/generate_embedded_templates.ts. Do not edit directly.

const embeddedTemplates = new Map<string, ReadonlyMap<string, string>>([
${entries}
]);

export function getEmbeddedTemplate(
  blockName: string,
  templatePath: string,
): string | undefined {
  return embeddedTemplates.get(blockName)?.get(templatePath);
}

export function listEmbeddedTemplateKeys(): string[] {
  return [...embeddedTemplates.entries()].flatMap(([blockName, templates]) =>
    [...templates.keys()].map((templatePath) => \`\${blockName}/\${templatePath}\`)
  ).sort();
}
`;
}

async function formatSource(source: string): Promise<string> {
  const command = new Deno.Command(Deno.execPath(), {
    args: ["fmt", "-"],
    stdin: "piped",
    stdout: "piped",
    stderr: "piped",
  }).spawn();
  const writer = command.stdin.getWriter();
  await writer.write(new TextEncoder().encode(source));
  await writer.close();
  const output = await command.output();
  if (!output.success) {
    throw new Error(
      `failed to format embedded templates:\n${
        new TextDecoder().decode(output.stderr)
      }`,
    );
  }
  return new TextDecoder().decode(output.stdout);
}

const check = Deno.args.length === 1 && Deno.args[0] === "--check";
if ((!check && Deno.args.length !== 0) || (check && Deno.args.length !== 1)) {
  throw new Error("usage: generate_embedded_templates.ts [--check]");
}

const generated = await formatSource(
  renderEmbeddedTemplates(await collectEmbeddedBlocks()),
);
if (check) {
  const committed = await Deno.readTextFile(outputPath);
  if (committed !== generated) {
    throw new Error(
      "embedded templates are stale; run `deno task embed` and commit the result",
    );
  }
} else {
  await Deno.writeTextFile(outputPath, generated);
}
