import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import {
  createExecutablePlan,
  executeInstallPlan,
} from "../packages/cli/src/executor.ts";

const CLI_VERSION = "0.2.0";
const DENO_VERSION = "2.9.3";
const repositoryRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const upstreamRoot = join(repositoryRoot, "tests", "fixtures", "upstream");
const goldenRoot = join(repositoryRoot, "tests", "golden");
const exampleRoot = join(repositoryRoot, "examples", "with-supabase");
const outputs = [
  {
    name: "client",
    source: join(upstreamRoot, "fresh-2.3.3-no-tailwind"),
    target: join(goldenRoot, "client"),
    block: "client",
  },
  {
    name: "password-based-auth",
    source: join(upstreamRoot, "fresh-2.3.3-tailwind"),
    target: join(goldenRoot, "password-based-auth"),
    block: "password-based-auth",
  },
  {
    name: "example-with-supabase",
    source: join(upstreamRoot, "fresh-2.3.3-tailwind"),
    target: exampleRoot,
    block: "password-based-auth",
  },
] as const;

async function targetExists(path: string): Promise<boolean> {
  try {
    await Deno.lstat(path);
    return true;
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return false;
    throw error;
  }
}

async function ensureEmptyDirectory(path: string): Promise<void> {
  if (!(await targetExists(path))) {
    await Deno.mkdir(path, { recursive: true });
    return;
  }
  const info = await Deno.lstat(path);
  if (!info.isDirectory) {
    throw new Error(`output target is not a directory: ${path}`);
  }
  for await (const entry of Deno.readDir(path)) {
    throw new Error(
      `output target is not empty (${entry.name}); generation refuses to overwrite committed evidence: ${path}`,
    );
  }
}

async function copyTreeContents(source: string, target: string): Promise<void> {
  const entries = [];
  for await (const entry of Deno.readDir(source)) entries.push(entry);
  entries.sort((a, b) => a.name.localeCompare(b.name));
  for (const entry of entries) {
    const sourcePath = join(source, entry.name);
    const targetPath = join(target, entry.name);
    if (entry.isDirectory) {
      await Deno.mkdir(targetPath);
      await copyTreeContents(sourcePath, targetPath);
    } else if (entry.isFile) {
      await Deno.copyFile(sourcePath, targetPath);
    } else {
      throw new Error(`unexpected non-file fixture entry: ${sourcePath}`);
    }
  }
}

async function sha256(bytes: Uint8Array): Promise<string> {
  return new Uint8Array(
    await crypto.subtle.digest("SHA-256", Uint8Array.from(bytes)),
  ).toHex();
}

async function fileHashes(
  directory: string,
  ignoredTopLevel: ReadonlySet<string> = new Set(),
): Promise<Record<string, string>> {
  const hashes: Record<string, string> = {};
  const visit = async (current: string): Promise<void> => {
    const entries = [];
    for await (const entry of Deno.readDir(current)) entries.push(entry);
    entries.sort((a, b) => a.name.localeCompare(b.name));
    for (const entry of entries) {
      if (current === directory && ignoredTopLevel.has(entry.name)) continue;
      const target = join(current, entry.name);
      if (entry.isDirectory) {
        await visit(target);
      } else if (entry.isFile) {
        hashes[relative(directory, target).replaceAll("\\", "/")] =
          await sha256(
            await Deno.readFile(target),
          );
      } else {
        throw new Error(`unexpected non-file output entry: ${target}`);
      }
    }
  };
  await visit(directory);
  return hashes;
}

if (Deno.args.length !== 0) {
  throw new Error("golden and example generation takes no arguments");
}
if (Deno.version.deno !== DENO_VERSION) {
  throw new Error(
    `example generation requires Deno ${DENO_VERSION}; found ${Deno.version.deno}`,
  );
}

for (const output of outputs) {
  if (!(await targetExists(output.source))) {
    throw new Error(
      `required committed upstream fixture is missing: ${output.source}`,
    );
  }
  await ensureEmptyDirectory(output.target);
  await copyTreeContents(output.source, output.target);
  const plan = await createExecutablePlan(
    output.target,
    output.block,
    CLI_VERSION,
  );
  if (plan.installPlan.issues.length > 0) {
    throw new Error(
      `${output.name} preflight failed: ${
        JSON.stringify(plan.installPlan.issues)
      }`,
    );
  }
  const result = await executeInstallPlan(plan);
  if (!result.changed) {
    throw new Error(`${output.name} generation unexpectedly made no changes`);
  }
}

await Deno.writeTextFile(
  join(exampleRoot, "README.md"),
  `# Fresh + Supabase password authentication

This example starts from the pinned official Fresh 2.3.3 Tailwind fixture and is
generated by this repository's \`@fresh-supabase/cli\` implementation. It uses
server-rendered Preact forms, POST + 303 redirects, request-scoped Supabase
clients, path-scoped CSRF, upstream-aligned global auth middleware, and no
runtime CLI dependency. Its 17 generated source files map one-to-one to Supabase
UI's upstream \`password-based-auth-nextjs\` block.

The root middleware commits Supabase's pending cookie and cache-header changes,
and the protected route reuses its verified claims without a second identity
request. Logout uses Supabase's \`local\` scope. Password length and complexity
are enforced by the connected Supabase project's policy.

## Configure

Copy \`.env.example\` to a local environment file and set:

- \`FRESH_PUBLIC_SUPABASE_URL\`;
- \`FRESH_PUBLIC_SUPABASE_PUBLISHABLE_KEY\`.

Configure Supabase's confirmation email template to send \`token_hash\` and \`type\`
to \`/auth/confirm\`, following the Supabase SSR guide.

## Run

\`\`\`bash
deno install --frozen
deno task --env-file dev
\`\`\`

The login page is at \`/auth/login\`; the protected page is at \`/protected\`.
Anonymous application and API requests outside \`/auth*\` and \`/login*\` are
redirected globally to the login page, matching the upstream block.

## Verify

\`\`\`bash
deno task check
deno task --env-file build
\`\`\`

The repository's integration suite additionally checks the committed structure,
a mocked Supabase password-auth flow, and a Deno Deploy-mode build.
`,
);

const standaloneRoot = await Deno.makeTempDir({
  prefix: "fresh-supabase-example-lock-",
});
try {
  await copyTreeContents(exampleRoot, standaloneRoot);
  const standaloneInstall = await new Deno.Command(Deno.execPath(), {
    args: ["install", "--minimum-dependency-age=0"],
    cwd: standaloneRoot,
    stdout: "piped",
    stderr: "piped",
  }).output();
  if (!standaloneInstall.success) {
    const decoder = new TextDecoder();
    throw new Error(
      `standalone example lock generation failed:\n${
        decoder.decode(standaloneInstall.stdout)
      }${decoder.decode(standaloneInstall.stderr)}`,
    );
  }
  await Deno.copyFile(
    join(standaloneRoot, "deno.lock"),
    join(exampleRoot, "deno.lock"),
  );
} finally {
  await Deno.remove(standaloneRoot, { recursive: true });
}

const goldenFiles: Record<string, Record<string, string>> = {};
for (const output of outputs.slice(0, 2)) {
  goldenFiles[output.name] = await fileHashes(output.target);
}
await Deno.writeTextFile(
  join(goldenRoot, "provenance.json"),
  JSON.stringify(
    {
      schemaVersion: 1,
      cliVersion: CLI_VERSION,
      sourceFixtures: {
        "client": "../fixtures/upstream/fresh-2.3.3-no-tailwind",
        "password-based-auth": "../fixtures/upstream/fresh-2.3.3-tailwind",
      },
      generation: {
        command:
          "deno run --no-config --no-lock --allow-read --allow-write --allow-run=deno scripts/generate_golden_and_example.ts",
        overwrite: false,
      },
      files: goldenFiles,
    },
    null,
    2,
  ) + "\n",
);

await Deno.writeTextFile(
  join(repositoryRoot, "examples", "provenance.json"),
  JSON.stringify(
    {
      schemaVersion: 1,
      cliVersion: CLI_VERSION,
      denoVersion: DENO_VERSION,
      sourceFixture: "../tests/fixtures/upstream/fresh-2.3.3-tailwind",
      requestedBlock: "password-based-auth",
      dependencyLockGeneratedWithMinimumAgeSeconds: 0,
      standaloneLockSha256: await sha256(
        await Deno.readFile(join(exampleRoot, "deno.lock")),
      ),
      ignoredGeneratedDirectories: ["_fresh", "node_modules"],
      files: await fileHashes(
        exampleRoot,
        new Set(["_fresh", "node_modules"]),
      ),
    },
    null,
    2,
  ) + "\n",
);
